course_dict = {
    33: 'Teknologi Produksi Biofuel',
    171: 'Desain Animasi & Multimedia',
    8014: 'Layanan Sosial (Malam)',
    9003: 'Agronomi',
    9070: 'Desain Komunikasi',
    9085: 'Keperawatan Hewan',
    9119: 'Teknik Informatika',
    9130: 'Kuda & Berkuda',
    9147: 'Manajemen',
    9238: 'Layanan Sosial',
    9254: 'Pariwisata',
    9500: 'Keperawatan',
    9556: 'Kebersihan Gigi',
    9670: 'Manajemen Periklanan',
    9773: 'Jurnalisme & Komunikasi',
    9853: 'Pendidikan Dasar',
    9991: 'Manajemen (Malam)'
}

nacionality_dict = {
    1: 'Portugis',
    2: 'Jerman',
    6: 'Spanyol',
    11: 'Italia',
    13: 'Belanda',
    14: 'Inggris',
    17: 'Lituania',
    21: 'Angola',
    22: 'Tanjung Verde',
    24: 'Guinea',
    25: 'Mozambik',
    26: 'Sao Tome',
    32: 'Turki',
    41: 'Brasil',
    62: 'Rumania',
    100: 'Moldova',
    101: 'Meksiko',
    103: 'Ukraina',
    105: 'Rusia',
    108: 'Kuba',
    109: 'Kolombia'
}

app_mode_dict = {
    1: 'Fase 1 - Umum',
    2: 'Ordinance 612/93',
    5: 'Fase 1 - Khusus (Azores)',
    7: 'Lulusan PT Lain',
    10: 'Ordinance 854-B/99',
    15: 'Mahasiswa Internasional',
    16: 'Fase 1 - Khusus (Madeira)',
    17: 'Fase 2 - Umum',
    18: 'Fase 3 - Umum',
    26: 'Ordinance 533-A/99 (B2)',
    27: 'Ordinance 533-A/99 (B3)',
    39: 'Usia > 23 Tahun',
    42: 'Transfer',
    43: 'Pindah Jurusan',
    44: 'Diploma Spesialisasi Teknologi',
    51: 'Pindah Kampus/Jurusan',
    53: 'Diploma Siklus Pendek',
    57: 'Pindah Kampus Internasional'
}

prev_qual_dict = {
    1: 'Pendidikan Menengah',
    2: 'Sarjana (S1)',
    3: 'Gelar Pendidikan Tinggi',
    4: 'Magister (S2)',
    5: 'Doktor (S3)',
    6: 'Pernah Kuliah',
    9: 'Kelas 12 (Tidak Tamat)',
    10: 'Kelas 11 (Tidak Tamat)',
    12: 'Lainnya - Kelas 11',
    14: 'Kelas 10',
    15: 'Kelas 10 (Tidak Tamat)',
    19: 'Pend. Dasar 3',
    38: 'Pend. Dasar 2',
    39: 'Spesialisasi Teknologi',
    40: 'Sarjana (S1)',
    42: 'Kursus Teknis Prof.',
    43: 'Magister (S2)'
}

feature_names_dict = {
    'Marital_status': 'Status Pernikahan',
    'Application_mode': 'Jalur Pendaftaran',
    'Application_order': 'Urutan Pilihan Prodi',
    'Course': 'Program Studi',
    'Daytime_evening_attendance': 'Waktu Kuliah',
    'Previous_qualification': 'Pendidikan Sebelumnya',
    'Previous_qualification_grade': 'Nilai Pendidikan Sebelumnya',
    'Nacionality': 'Kewarganegaraan',
    'Mothers_qualification': 'Pendidikan Ibu',
    'Fathers_qualification': 'Pendidikan Ayah',
    'Mothers_occupation': 'Pekerjaan Ibu',
    'Admission_grade': 'Nilai Masuk Ujian',
    'Displaced': 'Status Pendatang',
    'Educational_special_needs': 'Kebutuhan Khusus Pendidikan',
    'Debtor': 'Status Berutang',
    'Tuition_fees_up_to_date': 'Status Pembayaran SPP',
    'Gender': 'Jenis Kelamin',
    'Scholarship_holder': 'Penerima Beasiswa',
    'Age_at_enrollment': 'Usia Saat Mendaftar',
    'International': 'Mahasiswa Internasional',
    'Curricular_units_1st_sem_credited': 'SKS Diakui (Semester 1)',
    'Curricular_units_1st_sem_enrolled': 'SKS Diambil (Semester 1)',
    'Curricular_units_1st_sem_evaluations': 'Jumlah Evaluasi (Semester 1)',
    'Curricular_units_1st_sem_approved': 'SKS Lulus (Semester 1)',
    'Curricular_units_1st_sem_grade': 'Rata-rata Nilai Semester 1',
    'Curricular_units_1st_sem_without_evaluations': 'SKS Tanpa Evaluasi (Semester 1)',
    'Curricular_units_2nd_sem_evaluations': 'Jumlah Evaluasi (Semester 2)',
    'Curricular_units_2nd_sem_grade': 'Rata-rata Nilai Semester 2',
    'Curricular_units_2nd_sem_without_evaluations': 'SKS Tanpa Evaluasi (Semester 2)',
    'Unemployment_rate': 'Tingkat Pengangguran',
    'Inflation_rate': 'Tingkat Inflasi',
    'GDP': 'PDB (Produk Domestik Bruto)'
}

macro_data_dict = {
    '2018 (Ekonomi Stabil)': {'unemployment': 7.1, 'inflation': 1.0, 'gdp': 2.8},
    '2019 (Ekonomi Tumbuh)': {'unemployment': 6.6, 'inflation': 0.3, 'gdp': 2.7},
    '2020 (Krisis Pandemi COVID-19)': {'unemployment': 7.0, 'inflation': -0.1, 'gdp': -8.3},
    '2021 (Pemulihan Pasca Pandemi)': {'unemployment': 6.6, 'inflation': 1.3, 'gdp': 5.5},
    '2022 (Krisis Inflasi Global)': {'unemployment': 6.1, 'inflation': 7.8, 'gdp': 6.7},
    '2023 (Penyesuaian Ekonomi)': {'unemployment': 6.5, 'inflation': 4.3, 'gdp': 2.3},
    'Input Manual (Kustom)': {'unemployment': 10.8, 'inflation': 1.4, 'gdp': 1.74}
}

tooltips_dict = {
    'Age_at_enrollment': 'Usia mahasiswa saat pertama kali mendaftar ke perguruan tinggi.',
    'Gender': 'Jenis kelamin mahasiswa berdasarkan data pendaftaran.',
    'Marital_status': 'Status pernikahan mahasiswa saat mendaftar.',
    'Nacionality': 'Kewarganegaraan mahasiswa.',
    'International': 'Menandakan apakah mahasiswa berasal dari luar negeri.',
    'Mothers_qualification': 'Tingkat pendidikan terakhir ibu mahasiswa (dalam kode dataset).',
    'Fathers_qualification': 'Tingkat pendidikan terakhir ayah mahasiswa (dalam kode dataset).',
    'Mothers_occupation': 'Jenis pekerjaan ibu mahasiswa (dalam kode dataset).',
    'Application_mode': 'Jalur masuk yang digunakan mahasiswa (misal: Jalur Umum, Pindahan, Mahasiswa Internasional).',
    'Application_order': 'Urutan pilihan program studi saat mendaftar (0 = Pilihan Pertama, 9 = Pilihan Terakhir).',
    'Course': 'Program studi yang dipilih saat pendaftaran.',
    'Previous_qualification': 'Jenjang pendidikan terakhir sebelum masuk perguruan tinggi ini.',
    'Previous_qualification_grade': 'Nilai akhir dari jenjang pendidikan sebelumnya.',
    'Admission_grade': 'Nilai seleksi/ujian masuk perguruan tinggi.',
    'Daytime_evening_attendance': 'Waktu perkuliahan yang diambil mahasiswa (siang atau malam).',
    'Displaced': 'Apakah mahasiswa ini adalah pendatang dari luar kota/daerah asal kampus?',
    'Educational_special_needs': 'Apakah mahasiswa membutuhkan fasilitas pendidikan khusus (misal: disabilitas)?',
    'Debtor': 'Apakah mahasiswa ini tercatat memiliki utang atau tagihan tertunda di sistem kampus?',
    'Tuition_fees_up_to_date': 'Apakah pembayaran SPP mahasiswa ini lancar (tidak ada tunggakan sampai saat ini)?',
    'Scholarship_holder': 'Apakah mahasiswa menerima beasiswa pada periode studi berjalan?',
    'Curricular_units_credited': 'Jumlah SKS dari pendidikan sebelumnya yang diakui/ditransfer ke kampus ini.',
    'Curricular_units_enrolled': 'Jumlah total SKS yang didaftarkan/diambil mahasiswa pada semester tersebut.',
    'Curricular_units_evaluations': 'Jumlah ujian/evaluasi yang diikuti mahasiswa pada semester tersebut.',
    'Curricular_units_grade': 'Rata-rata nilai mata kuliah pada semester terkait.',
    'Curricular_units_approved': 'Jumlah SKS yang berhasil LULUS pada semester tersebut.',
    'Curricular_units_without_evaluations': 'Jumlah SKS yang diambil tapi tidak ada nilai evaluasinya (misal bolos ujian atau ditarik).',
    'Macro_Preset': 'Pilih kondisi ekonomi makro saat mahasiswa ini mendaftar. Sistem akan otomatis mengisi nilai Inflasi, Pengangguran, dan PDB.'
}

parents_edu_dict = {
    1: 'Pendidikan Menengah (SMA/Sederajat)',
    2: 'Sarjana (S1)',
    3: 'Pendidikan Tinggi',
    4: 'Magister (S2)',
    5: 'Doktor (S3)',
    6: 'Pernah Kuliah (Tidak Tamat)', 
    9: 'Kelas 12 (Tidak Tamat)',
    10: 'Kelas 11 (Tidak Tamat)',
    11: 'Kelas 7 (Tidak Tamat)',
    12: 'Lainnya - Kelas 11',
    14: 'Kelas 10',
    18: 'Pendidikan Umum',
    19: 'Pendidikan Dasar', 
    22: 'Pendidikan Teknis',
    26: 'Kelas 7',
    27: 'Kelas 2',
    29: 'Kelas 9', 
    30: 'Kelas 8',
    34: 'Tidak Diketahui',
    35: 'Belum Bisa Membaca/Menulis', 
    36: 'Bisa Membaca/Menulis',
    37: 'Pendidikan Dasar (Kelas 1)', 
    38: 'Pendidikan Dasar (Kelas 2)',
    39: 'Spesialisasi Teknologi', 
    40: 'Sarjana (S1)',
    41: 'Magister (S2)',
    42: 'Kursus Teknis Profesional', 
    43: 'Magister Khusus',
    44: 'Doktor Khusus',
}

parents_job_dict = {
    0: 'Pelajar / Mahasiswa',
    1: 'Pejabat Eksekutif / Legislatif',
    2: 'Spesialis (Intelektual & Sains)', 
    3: 'Teknisi Tingkat Menengah',
    4: 'Staf Administrasi',
    5: 'Pekerja Jasa & Penjualan', 
    6: 'Petani & Pekerja Pertanian',
    7: 'Pekerja Industri & Konstruksi',
    8: 'Operator Mesin & Pabrik',
    9: 'Pekerja Kasar / Tidak Terampil',
    10: 'Angkatan Bersenjata (TNI/Polri)',
    90: 'Lainnya', 
    99: 'Tidak Diketahui',
    122: 'Tenaga Kesehatan',
    123: 'Guru / Pendidik', 
    125: 'Pakar IT & Komunikasi',
    131: 'Petani Spesialis',
    132: 'Pekerja Pertanian/Kehutanan', 
    134: 'Pekerja Jasa Pelindungan',
    141: 'Pekerja Logistik/Administrasi',
    143: 'Operator Pengolahan Data', 
    144: 'Sekretaris',
    151: 'Pekerja IT',
    152: 'Pekerja Jasa Lainnya',
    153: 'Pekerja Konstruksi',
    171: 'Pekerja Pabrik',
    173: 'Pengrajin',
    175: 'Pekerja Pabrik Makanan',
    191: 'Pekerja Kebersihan', 
    192: 'Pekerja Kasar Pertanian',
    193: 'Pekerja Kasar Industri',
    194: 'Pekerja Bangunan',
    195: 'Pekerja Pemeliharaan',
}